---
# Check CHANGELOG.md file updated for every pull request

name: Changelog Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    name: Changelog Update Check
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Job automatically triggered by ${{ github.event_name }}"
      - run: echo "🐧 Job running on ${{ runner.os }} server"
      - run: echo "🐙 Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            CHANGELOG.md
      - run: echo "🐙 ${{ github.repository }} repository sparse-checkout to the CI runner."

      - name: Changelog Enforcer
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: "CHANGELOG.md"
          skipLabels: "skip-changelog-check"

      # Summary and status
      - run: echo "🎨 Changelog Enforcer quality checks completed"
      - run: echo "🍏 Job status is ${{ job.status }}."
